name: My workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: List and Read
          run: |
                 echo "my first one"
                 ls -ltrals
                 cat README.md

       # - name: List file
       #   run: 

        #- name: Read the file
         # run: cat README.md
    