name: My workflow

on: push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: welcome Ahmmed
          run: echo " hey bud"


        - name: List file
          run: ls

        - name: Read the file
          run: cat README.md
    