name: Generate ASCII Artwork

on: 
  workflow_dispatch: 

jobs: 
    build_job_1: 
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon.. RAWR" >> dragon.txt
          
        - name: Upload Dragon file
          uses: actions/upload-artifact@v4
          with:
              name: dragon-text
              path: dragon.txt
            
    test_job_2: 
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download Draagon file
          uses: actions/download-artifact@v4
          with:
              name: dragon-text
              

        - name: Test file exists
          run: grep -i "dragon" dragon.txt
        
    deply_job_3: 
        needs: test_job_2
        concurrency: 
          group: prod-deploynet
          cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:

        - name: Download Dragon file
          uses: actions/download-artifact@v4
          with:
              name: dragon-text
             

        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: |
            echo deploying....
            sleep 600s
        
          
       


         
            