name: Exploring Var and Secrets 

on: 
    push

env:
      IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
     
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      env:
        DOCKER_PASSWORD: s3cUrePaSsw0rd
      run: echo docker login --username=$DOCKER_USERNAM --passwrod=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker publish
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

